name: 🐞 Bug Report
description: Segnala un problema o un malfunzionamento in Dromi
title: "[BUG] Breve descrizione del problema"
labels: [bug]
assignees: []

body:
  - type: textarea
    id: descrizione_problema
    attributes:
      label: Descrizione del problema
      description: Una descrizione chiara e concisa del bug.
      placeholder: Inserisci qui il dettaglio del bug
    validations:
      required: true

  - type: textarea
    id: codice_errore
    attributes:
      label: Codice che dà l'errore
      description: Il codice per far apparire il bug, ad esempio:
      placeholder: |
        form mdl import akdir
        akdir.copydir("sns", "snscopy") # Qui
    validations:
      required: true

  - type: textarea
    id: comportamento_atteso
    attributes:
      label: Comportamento atteso
      description: Descrivi cosa ti aspettavi che accadesse.
      placeholder: Inserisci qui il comportamento atteso
    validations:
      required: true

  - type: textarea
    id: comportamento_attuale
    attributes:
      label: Comportamento attuale
      description: Cosa succede realmente.
      placeholder: Inserisci qui il comportamento reale
    validations:
      required: true

  - type: input
    id: versione_dromi
    attributes:
      label: Versione Dromi
      description: La versione di Dromi in uso
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: sistema_operativo
    attributes:
      label: Sistema operativo
      description: Seleziona il sistema operativo in uso
      options:
        - Windows 10
        - Windows 11
    validations:
      required: true

  - type: textarea
    id: log_screenshot
    attributes:
      label: Log / Screenshot
      description: Allega eventuali log, errori o screenshot
      placeholder: Inserisci link o testo dei log

  - type: textarea
    id: note_aggiuntive
    attributes:
      label: Note aggiuntive
      description: Qualsiasi altra informazione utile
      placeholder: Inserisci qui note aggiuntive
