name: PR Logger

on:
  pull_request:
    types: [opened]

permissions:
  contents: write

jobs:
  log-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Clona repo
        uses: actions/checkout@v3

      - name: Crea file PR
        run: |
          echo "Workflow PULL REQUEST in corso"
          mkdir -p .github/prs

          code=$RANDOM
          filename=".github/prs/NEW_PULL_REQUEST_$code.pr"

          echo "NEW PULL REQUEST" > $filename
          echo "Code: $code" >> $filename
          echo "Autore: ${{ github.actor }}" >> $filename
          echo "Data: $(date)" >> $filename

      - name: Commit e push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/prs/
          git commit -m "Nuova PR loggata" || echo "Niente da committare"
          git push
